
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 31 20:47:37 CST 2025
//----------------------------------------------------

package analizadorlexico;

import java_cup.runtime.Symbol;
import analizadorlexico.Errores;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Aug 31 20:47:37 CST 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\131\000\002\002\004\000\002\002\010\000\002\002" +
    "\010\000\002\003\004\000\002\003\003\000\002\003\004" +
    "\000\002\003\003\000\002\003\004\000\002\003\003\000" +
    "\002\003\004\000\002\003\003\000\002\003\004\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\004" +
    "\005\000\002\004\011\000\002\004\007\000\002\004\005" +
    "\000\002\004\007\000\002\004\007\000\002\004\005\000" +
    "\002\004\010\000\002\004\011\000\002\004\007\000\002" +
    "\004\007\000\002\014\003\000\002\014\005\000\002\015" +
    "\010\000\002\016\006\000\002\016\006\000\002\016\004" +
    "\000\002\017\003\000\002\017\003\000\002\020\005\000" +
    "\002\020\005\000\002\020\005\000\002\020\005\000\002" +
    "\020\005\000\002\020\005\000\002\020\005\000\002\020" +
    "\005\000\002\020\005\000\002\020\005\000\002\020\005" +
    "\000\002\020\005\000\002\020\003\000\002\006\013\000" +
    "\002\006\013\000\002\006\013\000\002\006\013\000\002" +
    "\012\003\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\005\000\002\012\006\000\002\012\006" +
    "\000\002\012\007\000\002\007\020\000\002\010\013\000" +
    "\002\011\013\000\002\013\012\000\002\013\011\000\002" +
    "\005\004\000\002\005\004\000\002\021\006\000\002\021" +
    "\006\000\002\023\003\000\002\023\005\000\002\024\003" +
    "\000\002\024\005\000\002\025\010\000\002\025\011\000" +
    "\002\025\006\000\002\025\006\000\002\025\007\000\002" +
    "\025\010\000\002\025\006\000\002\025\006\000\002\025" +
    "\005\000\002\026\007\000\002\026\007\000\002\027\005" +
    "\000\002\027\005\000\002\027\007\000\002\027\005\000" +
    "\002\022\003\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\353\000\004\025\005\001\002\000\004\002\355\001" +
    "\002\000\004\011\006\001\002\000\004\004\007\001\002" +
    "\000\022\017\021\020\015\021\024\023\027\027\013\031" +
    "\012\032\025\044\026\001\002\000\020\012\ufff7\017\ufff7" +
    "\020\ufff7\021\ufff7\027\ufff7\031\ufff7\032\ufff7\001\002\000" +
    "\020\012\ufff5\017\ufff5\020\ufff5\021\ufff5\027\ufff5\031\ufff5" +
    "\032\ufff5\001\002\000\004\007\345\001\002\000\004\007" +
    "\310\001\002\000\020\012\ufffd\017\ufffd\020\ufffd\021\ufffd" +
    "\027\ufffd\031\ufffd\032\ufffd\001\002\000\004\044\273\001" +
    "\002\000\020\012\ufff4\017\ufff4\020\ufff4\021\ufff4\027\ufff4" +
    "\031\ufff4\032\ufff4\001\002\000\020\012\ufff3\017\ufff3\020" +
    "\ufff3\021\ufff3\027\ufff3\031\ufff3\032\ufff3\001\002\000\020" +
    "\012\ufff9\017\ufff9\020\ufff9\021\ufff9\027\ufff9\031\ufff9\032" +
    "\ufff9\001\002\000\004\044\262\001\002\000\020\012\ufffb" +
    "\017\ufffb\020\ufffb\021\ufffb\027\ufffb\031\ufffb\032\ufffb\001" +
    "\002\000\020\012\257\017\021\020\015\021\024\027\013" +
    "\031\012\032\025\001\002\000\006\003\246\044\247\001" +
    "\002\000\004\007\172\001\002\000\010\013\103\033\104" +
    "\041\102\001\002\000\004\007\030\001\002\000\014\006" +
    "\032\007\033\011\034\044\037\045\031\001\002\000\024" +
    "\003\uffe1\004\uffe1\010\uffe1\012\uffe1\014\uffe1\015\uffe1\034" +
    "\uffe1\035\uffe1\036\uffe1\001\002\000\004\044\075\001\002" +
    "\000\014\003\070\007\033\011\034\044\054\045\031\001" +
    "\002\000\014\003\063\007\033\011\034\044\054\045\031" +
    "\001\002\000\024\003\uffd3\004\uffd3\010\uffd3\012\uffd3\014" +
    "\uffd3\015\uffd3\034\uffd3\035\uffd3\036\uffd3\001\002\000\012" +
    "\010\061\034\050\035\047\036\051\001\002\000\014\010" +
    "\uffe0\034\uffe0\035\uffe0\036\uffe0\043\043\001\002\000\004" +
    "\010\041\001\002\000\004\004\042\001\002\000\020\012" +
    "\uffb0\017\uffb0\020\uffb0\021\uffb0\027\uffb0\031\uffb0\032\uffb0" +
    "\001\002\000\014\006\032\007\033\011\034\044\037\045" +
    "\031\001\002\000\012\010\uffaa\034\050\035\047\036\051" +
    "\001\002\000\004\010\uffab\001\002\000\004\010\uffa9\001" +
    "\002\000\014\003\057\007\033\011\034\044\054\045\031" +
    "\001\002\000\014\003\055\007\033\011\034\044\054\045" +
    "\031\001\002\000\014\003\052\007\033\011\034\044\054" +
    "\045\031\001\002\000\024\003\uffda\004\uffda\010\uffda\012" +
    "\uffda\014\uffda\015\uffda\034\uffda\035\uffda\036\uffda\001\002" +
    "\000\024\003\uffdb\004\uffdb\010\uffdb\012\uffdb\014\uffdb\015" +
    "\uffdb\034\uffdb\035\uffdb\036\uffdb\001\002\000\024\003\uffe0" +
    "\004\uffe0\010\uffe0\012\uffe0\014\uffe0\015\uffe0\034\uffe0\035" +
    "\uffe0\036\uffe0\001\002\000\024\003\uffde\004\uffde\010\uffde" +
    "\012\uffde\014\uffde\015\uffde\034\uffde\035\uffde\036\uffde\001" +
    "\002\000\024\003\uffdf\004\uffdf\010\uffdf\012\uffdf\014\uffdf" +
    "\015\uffdf\034\uffdf\035\uffdf\036\051\001\002\000\024\003" +
    "\uffdc\004\uffdc\010\uffdc\012\uffdc\014\uffdc\015\uffdc\034\uffdc" +
    "\035\uffdc\036\uffdc\001\002\000\024\003\uffdd\004\uffdd\010" +
    "\uffdd\012\uffdd\014\uffdd\015\uffdd\034\uffdd\035\uffdd\036\051" +
    "\001\002\000\004\004\062\001\002\000\020\012\uffaf\017" +
    "\uffaf\020\uffaf\021\uffaf\027\uffaf\031\uffaf\032\uffaf\001\002" +
    "\000\004\012\067\001\002\000\014\003\066\012\065\034" +
    "\050\035\047\036\051\001\002\000\024\003\uffd6\004\uffd6" +
    "\010\uffd6\012\uffd6\014\uffd6\015\uffd6\034\uffd6\035\uffd6\036" +
    "\uffd6\001\002\000\024\003\uffd5\004\uffd5\010\uffd5\012\uffd5" +
    "\014\uffd5\015\uffd5\034\uffd5\035\uffd5\036\uffd5\001\002\000" +
    "\024\003\uffd4\004\uffd4\010\uffd4\012\uffd4\014\uffd4\015\uffd4" +
    "\034\uffd4\035\uffd4\036\uffd4\001\002\000\004\010\074\001" +
    "\002\000\014\003\072\010\073\034\050\035\047\036\051" +
    "\001\002\000\024\003\uffd8\004\uffd8\010\uffd8\012\uffd8\014" +
    "\uffd8\015\uffd8\034\uffd8\035\uffd8\036\uffd8\001\002\000\024" +
    "\003\uffd9\004\uffd9\010\uffd9\012\uffd9\014\uffd9\015\uffd9\034" +
    "\uffd9\035\uffd9\036\uffd9\001\002\000\024\003\uffd7\004\uffd7" +
    "\010\uffd7\012\uffd7\014\uffd7\015\uffd7\034\uffd7\035\uffd7\036" +
    "\uffd7\001\002\000\006\003\077\006\076\001\002\000\006" +
    "\010\uffae\043\100\001\002\000\004\010\uffad\001\002\000" +
    "\014\006\032\007\033\011\034\044\037\045\031\001\002" +
    "\000\004\010\uffac\001\002\000\004\004\171\001\002\000" +
    "\012\007\033\011\034\044\054\045\031\001\002\000\024" +
    "\006\114\007\033\011\034\013\107\022\110\024\111\042" +
    "\106\044\054\045\031\001\002\000\012\004\163\034\050" +
    "\035\047\036\051\001\002\000\004\004\162\001\002\000" +
    "\012\007\033\011\034\044\054\045\031\001\002\000\004" +
    "\007\137\001\002\000\004\007\124\001\002\000\004\004" +
    "\123\001\002\000\004\004\122\001\002\000\006\006\115" +
    "\044\116\001\002\000\004\004\121\001\002\000\004\006" +
    "\117\001\002\000\004\004\120\001\002\000\020\012\uffb4" +
    "\017\uffb4\020\uffb4\021\uffb4\027\uffb4\031\uffb4\032\uffb4\001" +
    "\002\000\020\012\uffb5\017\uffb5\020\uffb5\021\uffb5\027\uffb5" +
    "\031\uffb5\032\uffb5\001\002\000\020\012\uffb3\017\uffb3\020" +
    "\uffb3\021\uffb3\027\uffb3\031\uffb3\032\uffb3\001\002\000\020" +
    "\012\uffb2\017\uffb2\020\uffb2\021\uffb2\027\uffb2\031\uffb2\032" +
    "\uffb2\001\002\000\006\022\110\044\130\001\002\000\004" +
    "\010\136\001\002\000\006\010\uffbd\015\134\001\002\000" +
    "\004\010\133\001\002\000\006\010\uffbb\015\131\001\002" +
    "\000\004\044\130\001\002\000\004\010\uffba\001\002\000" +
    "\004\004\uffbf\001\002\000\004\022\110\001\002\000\004" +
    "\010\uffbc\001\002\000\004\004\uffbe\001\002\000\004\045" +
    "\140\001\002\000\004\044\153\001\002\000\010\033\144" +
    "\034\143\035\142\001\002\000\004\045\151\001\002\000" +
    "\004\045\147\001\002\000\004\045\145\001\002\000\004" +
    "\010\146\001\002\000\010\004\uffe5\010\uffe5\015\uffe5\001" +
    "\002\000\004\044\150\001\002\000\010\033\uffe4\034\uffe4" +
    "\035\uffe4\001\002\000\004\044\152\001\002\000\010\033" +
    "\uffe3\034\uffe3\035\uffe3\001\002\000\010\033\uffe2\034\uffe2" +
    "\035\uffe2\001\002\000\004\014\160\001\002\000\014\014" +
    "\uffe7\015\156\034\050\035\047\036\051\001\002\000\012" +
    "\007\033\011\034\044\054\045\031\001\002\000\004\014" +
    "\uffe6\001\002\000\004\004\161\001\002\000\020\012\uffb9" +
    "\017\uffb9\020\uffb9\021\uffb9\027\uffb9\031\uffb9\032\uffb9\001" +
    "\002\000\020\012\uffb6\017\uffb6\020\uffb6\021\uffb6\027\uffb6" +
    "\031\uffb6\032\uffb6\001\002\000\020\012\uffb7\017\uffb7\020" +
    "\uffb7\021\uffb7\027\uffb7\031\uffb7\032\uffb7\001\002\000\012" +
    "\014\165\034\050\035\047\036\051\001\002\000\004\033" +
    "\166\001\002\000\004\045\167\001\002\000\004\004\170" +
    "\001\002\000\020\012\uffb8\017\uffb8\020\uffb8\021\uffb8\027" +
    "\uffb8\031\uffb8\032\uffb8\001\002\000\020\012\uffb1\017\uffb1" +
    "\020\uffb1\021\uffb1\027\uffb1\031\uffb1\032\uffb1\001\002\000" +
    "\006\017\175\044\174\001\002\000\004\010\233\001\002" +
    "\000\004\033\225\001\002\000\004\044\176\001\002\000" +
    "\004\033\177\001\002\000\004\045\200\001\002\000\004" +
    "\016\201\001\002\000\006\042\203\044\204\001\002\000" +
    "\004\016\217\001\002\000\006\010\uffce\016\uffce\001\002" +
    "\000\004\041\205\001\002\000\014\003\210\006\207\042" +
    "\211\044\212\045\206\001\002\000\006\010\uffcb\016\uffcb" +
    "\001\002\000\006\006\214\044\215\001\002\000\010\006" +
    "\213\010\uffcc\016\uffcc\001\002\000\006\010\uffcd\016\uffcd" +
    "\001\002\000\006\010\uffca\016\uffca\001\002\000\006\010" +
    "\uffc8\016\uffc8\001\002\000\006\010\uffc9\016\uffc9\001\002" +
    "\000\004\006\216\001\002\000\006\010\uffc7\016\uffc7\001" +
    "\002\000\006\040\222\044\221\001\002\000\004\010\uffc3" +
    "\001\002\000\004\040\224\001\002\000\004\044\223\001" +
    "\002\000\004\010\uffc0\001\002\000\004\010\uffc1\001\002" +
    "\000\004\045\226\001\002\000\004\016\227\001\002\000" +
    "\006\042\203\044\204\001\002\000\004\016\231\001\002" +
    "\000\006\040\222\044\221\001\002\000\004\010\uffc2\001" +
    "\002\000\004\011\234\001\002\000\004\004\235\001\002" +
    "\000\022\017\021\020\015\021\024\023\027\027\013\031" +
    "\012\032\025\044\026\001\002\000\020\012\244\017\021" +
    "\020\015\021\024\027\013\031\012\032\025\001\002\000" +
    "\020\012\ufff8\017\ufff8\020\ufff8\021\ufff8\027\ufff8\031\ufff8" +
    "\032\ufff8\001\002\000\020\012\ufff6\017\ufff6\020\ufff6\021" +
    "\ufff6\027\ufff6\031\ufff6\032\ufff6\001\002\000\020\012\ufffe" +
    "\017\ufffe\020\ufffe\021\ufffe\027\ufffe\031\ufffe\032\ufffe\001" +
    "\002\000\020\012\ufffa\017\ufffa\020\ufffa\021\ufffa\027\ufffa" +
    "\031\ufffa\032\ufffa\001\002\000\020\012\ufffc\017\ufffc\020" +
    "\ufffc\021\ufffc\027\ufffc\031\ufffc\032\ufffc\001\002\000\004" +
    "\004\245\001\002\000\020\012\uffc4\017\uffc4\020\uffc4\021" +
    "\uffc4\027\uffc4\031\uffc4\032\uffc4\001\002\000\004\033\254" +
    "\001\002\000\006\004\250\033\251\001\002\000\020\012" +
    "\uffef\017\uffef\020\uffef\021\uffef\027\uffef\031\uffef\032\uffef" +
    "\001\002\000\004\042\252\001\002\000\004\004\253\001" +
    "\002\000\020\012\uffee\017\uffee\020\uffee\021\uffee\027\uffee" +
    "\031\uffee\032\uffee\001\002\000\004\042\255\001\002\000" +
    "\004\004\256\001\002\000\020\012\uffed\017\uffed\020\uffed" +
    "\021\uffed\027\uffed\031\uffed\032\uffed\001\002\000\006\003" +
    "\260\026\261\001\002\000\004\002\uffff\001\002\000\004" +
    "\002\000\001\002\000\006\004\263\033\264\001\002\000" +
    "\020\012\ufff2\017\ufff2\020\ufff2\021\ufff2\027\ufff2\031\ufff2" +
    "\032\ufff2\001\002\000\014\007\033\011\034\013\265\044" +
    "\054\045\031\001\002\000\012\007\033\011\034\044\054" +
    "\045\031\001\002\000\012\004\267\034\050\035\047\036" +
    "\051\001\002\000\020\012\ufff0\017\ufff0\020\ufff0\021\ufff0" +
    "\027\ufff0\031\ufff0\032\ufff0\001\002\000\004\014\271\001" +
    "\002\000\004\004\272\001\002\000\020\012\ufff1\017\ufff1" +
    "\020\ufff1\021\ufff1\027\ufff1\031\ufff1\032\ufff1\001\002\000" +
    "\006\004\274\033\275\001\002\000\020\012\uffec\017\uffec" +
    "\020\uffec\021\uffec\027\uffec\031\uffec\032\uffec\001\002\000" +
    "\010\006\277\022\110\024\111\001\002\000\004\004\307" +
    "\001\002\000\006\006\302\044\303\001\002\000\004\004" +
    "\301\001\002\000\020\012\uffe9\017\uffe9\020\uffe9\021\uffe9" +
    "\027\uffe9\031\uffe9\032\uffe9\001\002\000\004\004\306\001" +
    "\002\000\004\006\304\001\002\000\004\004\305\001\002" +
    "\000\020\012\uffea\017\uffea\020\uffea\021\uffea\027\uffea\031" +
    "\uffea\032\uffea\001\002\000\020\012\uffeb\017\uffeb\020\uffeb" +
    "\021\uffeb\027\uffeb\031\uffeb\032\uffeb\001\002\000\020\012" +
    "\uffe8\017\uffe8\020\uffe8\021\uffe8\027\uffe8\031\uffe8\032\uffe8" +
    "\001\002\000\010\003\312\042\203\044\204\001\002\000" +
    "\004\010\321\001\002\000\004\010\313\001\002\000\004" +
    "\011\314\001\002\000\004\004\315\001\002\000\022\017" +
    "\021\020\015\021\024\023\027\027\013\031\012\032\025" +
    "\044\026\001\002\000\020\012\317\017\021\020\015\021" +
    "\024\027\013\031\012\032\025\001\002\000\004\004\320" +
    "\001\002\000\020\012\uffd1\017\uffd1\020\uffd1\021\uffd1\027" +
    "\uffd1\031\uffd1\032\uffd1\001\002\000\006\003\323\011\322" +
    "\001\002\000\004\004\330\001\002\000\004\004\324\001" +
    "\002\000\022\017\021\020\015\021\024\023\027\027\013" +
    "\031\012\032\025\044\026\001\002\000\020\012\326\017" +
    "\021\020\015\021\024\027\013\031\012\032\025\001\002" +
    "\000\004\004\327\001\002\000\020\012\uffd0\017\uffd0\020" +
    "\uffd0\021\uffd0\027\uffd0\031\uffd0\032\uffd0\001\002\000\024" +
    "\003\332\017\021\020\015\021\024\023\027\027\013\031" +
    "\012\032\025\044\026\001\002\000\020\012\335\017\021" +
    "\020\015\021\024\027\013\031\012\032\025\001\002\000" +
    "\004\012\333\001\002\000\004\004\334\001\002\000\020" +
    "\012\uffcf\017\uffcf\020\uffcf\021\uffcf\027\uffcf\031\uffcf\032" +
    "\uffcf\001\002\000\006\004\336\030\337\001\002\000\020" +
    "\012\uffd2\017\uffd2\020\uffd2\021\uffd2\027\uffd2\031\uffd2\032" +
    "\uffd2\001\002\000\004\011\340\001\002\000\004\004\341" +
    "\001\002\000\022\017\021\020\015\021\024\023\027\027" +
    "\013\031\012\032\025\044\026\001\002\000\020\012\343" +
    "\017\021\020\015\021\024\027\013\031\012\032\025\001" +
    "\002\000\004\004\344\001\002\000\020\012\uffc6\017\uffc6" +
    "\020\uffc6\021\uffc6\027\uffc6\031\uffc6\032\uffc6\001\002\000" +
    "\006\042\203\044\204\001\002\000\004\010\347\001\002" +
    "\000\004\011\350\001\002\000\004\004\351\001\002\000" +
    "\022\017\021\020\015\021\024\023\027\027\013\031\012" +
    "\032\025\044\026\001\002\000\020\012\353\017\021\020" +
    "\015\021\024\027\013\031\012\032\025\001\002\000\004" +
    "\004\354\001\002\000\020\012\uffc5\017\uffc5\020\uffc5\021" +
    "\uffc5\027\uffc5\031\uffc5\032\uffc5\001\002\000\004\002\001" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\353\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\003\022\004\013" +
    "\006\021\007\017\010\007\011\010\025\015\026\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\240\006\242\007" +
    "\241\010\236\011\237\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\017" +
    "\034\020\035\027\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\017\034\020\070\001\001\000\006\017" +
    "\034\020\063\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\017\034\020\043\022\044\027\045" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\017\034\020\057\001\001\000\006\017\034" +
    "\020\055\001\001\000\006\017\034\020\052\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\017\034" +
    "\020\043\022\100\027\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\017\034\020\163\001\001\000\012" +
    "\015\112\017\034\020\104\021\111\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\014\153\017\034\020\154" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\015\125\023\126\024\124\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\024\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\125\023\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\140\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\014\156\017\034\020\154\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\172\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\201\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\217\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\227\001\001\000" +
    "\002\001\001\000\004\005\231\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\003\235\004" +
    "\013\006\021\007\017\010\007\011\010\025\015\026\016" +
    "\001\001\000\014\004\240\006\242\007\241\010\236\011" +
    "\237\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\017\034" +
    "\020\265\001\001\000\010\014\267\017\034\020\154\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\275\021\277\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\310\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\003\315\004" +
    "\013\006\021\007\017\010\007\011\010\025\015\026\016" +
    "\001\001\000\014\004\240\006\242\007\241\010\236\011" +
    "\237\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\324\004\013\006\021\007\017\010\007\011\010\025\015" +
    "\026\016\001\001\000\014\004\240\006\242\007\241\010" +
    "\236\011\237\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\003\330\004\013\006\021\007\017\010\007\011" +
    "\010\025\015\026\016\001\001\000\014\004\240\006\242" +
    "\007\241\010\236\011\237\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\341\004\013\006\021\007\017\010\007\011\010\025\015" +
    "\026\016\001\001\000\014\004\240\006\242\007\241\010" +
    "\236\011\237\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\345\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\003\351\004\013\006\021" +
    "\007\017\010\007\011\010\025\015\026\016\001\001\000" +
    "\014\004\240\006\242\007\241\010\236\011\237\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    
    public void syntax_error(java_cup.runtime.Symbol cur_token){
        // CUP ya tiene las posiciones exactas en cur_token.left y cur_token.right
        int linea = cur_token.right + 1;   // columna final del token
        int columna = cur_token.left + 1;  // columna inicial del token
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : "EOF";

        // CUP construye el mensaje listo en texto
        Errores.add("Error de sintaxis: Línea " + linea +
                    ", Columna " + columna +
                    ", Texto: \"" + lexema + "\"");
    }

    public Symbol getS(){
        return this.s;
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // EXPRESION_MENSAJES ::= MENSAJE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_MENSAJES",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // EXPRESION_MENSAJES ::= OPERACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_MENSAJES",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // MENSAJE ::= Identificador Concatenacion EXPRESION_MENSAJES 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MENSAJE",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // MENSAJE ::= Comillas Identificador Comillas Concatenacion EXPRESION_MENSAJES 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MENSAJE",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // MENSAJE ::= Comillas Identificador error 
            {
              Object RESULT =null;
		 
           Errores.add("True \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MENSAJE",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // MENSAJE ::= Comillas Identificador Comillas 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MENSAJE",21, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // MOSTRAR ::= Mostrar Parentesis_a OPERACION Parentesis_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MOSTRAR",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // MOSTRAR ::= Mostrar Parentesis_a MENSAJE Parentesis_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MOSTRAR",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // SENTENCIA_SIMPLE ::= Identificador Op_relacional Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // SENTENCIA_SIMPLE ::= Identificador Igual RESOLVER Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // SENTENCIA_SIMPLE ::= Identificador Igual ECUACION Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // SENTENCIA_SIMPLE ::= Identificador Igual Comillas Identificador Comillas Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // SENTENCIA_SIMPLE ::= Identificador Igual Comillas Comillas Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // SENTENCIA_SIMPLE ::= Identificador Igual Op_booleano Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // SENTENCIA_SIMPLE ::= Identificador Igual OPERACION Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // SENTENCIA_SIMPLE ::= Identificador Corchete_a OPERACION Corchete_c Igual Numero Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // SENTENCIA_SIMPLE ::= Identificador Igual Corchete_a LISTA_NUMEROS Corchete_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SIMPLE",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // LISTA_IDENTIFICADORES ::= Identificador Coma LISTA_IDENTIFICADORES 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_IDENTIFICADORES",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // LISTA_IDENTIFICADORES ::= Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_IDENTIFICADORES",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // LISTA_ECUACIONES ::= ECUACION Coma LISTA_ECUACIONES 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_ECUACIONES",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // LISTA_ECUACIONES ::= ECUACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_ECUACIONES",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // RESOLVER ::= ResolverSistema Parentesis_a LISTA_IDENTIFICADORES Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("RESOLVER",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // RESOLVER ::= ResolverSistema Parentesis_a LISTA_ECUACIONES Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("RESOLVER",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // DECLARACION_FOR ::= Op_incremento Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_FOR",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // DECLARACION_FOR ::= Identificador Op_incremento 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_FOR",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // SENTENCIA_FOR ::= Identificador Igual Numero P_coma SENTENCIA_BOOLEANA P_coma DECLARACION_FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // SENTENCIA_FOR ::= Num Identificador Igual Numero P_coma SENTENCIA_BOOLEANA P_coma DECLARACION_FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // FOR ::= For Parentesis_a SENTENCIA_FOR Parentesis_c Llave_a Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FOR",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // WHILE ::= While Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("WHILE",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // IF_ELSE ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a Linea SENTENCIA Llave_c Else Llave_a Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_ELSE",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-13)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Comillas Identificador Comillas 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional error Comillas 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera comillas despues del operador  \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Comillas Comillas 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Numero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera un operador al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Op_booleano 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // SENTENCIA_BOOLEANA ::= Op_booleano 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // IF ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a Linea error Llave_c Linea 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una sentencia entre las llaves \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // IF ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c error Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una llave despues del ultimo parentesis \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // IF ::= If Parentesis_a error Parentesis_c Llave_a Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una condicion entre los parentesis \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // IF ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a Linea SENTENCIA Llave_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // OPERACION ::= TERMINO 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // OPERACION ::= Llave_a error Llave_c 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una operacion entre las llaves \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // OPERACION ::= Llave_a OPERACION error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una llave al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // OPERACION ::= Llave_a OPERACION Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // OPERACION ::= Parentesis_a error Parentesis_c 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una operacion entre los parentesis \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // OPERACION ::= Parentesis_a OPERACION error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera un parentesis al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // OPERACION ::= Parentesis_a OPERACION Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // OPERACION ::= OPERACION Multiplicacion error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una operacion al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // OPERACION ::= OPERACION Multiplicacion OPERACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // OPERACION ::= OPERACION Resta error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una operacion al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // OPERACION ::= OPERACION Resta OPERACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OPERACION ::= OPERACION Suma error 
            {
              Object RESULT =null;
		 
           Errores.add("Se espera una operacion al final \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OPERACION ::= OPERACION Suma OPERACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("OPERACION",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // TERMINO ::= Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // TERMINO ::= Numero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESION ::= Numero Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION ::= EXPRESION Resta Numero Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESION ::= EXPRESION Suma Numero Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ECUACION ::= Ecuacion Parentesis_a EXPRESION Igual Numero Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ECUACION",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // LISTA_NUMEROS ::= OPERACION Coma LISTA_NUMEROS 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_NUMEROS",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // LISTA_NUMEROS ::= OPERACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_NUMEROS",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DECLARACION ::= Cadena Identificador Igual ECUACION Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARACION ::= Cadena Identificador Igual RESOLVER Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARACION ::= Cadena Identificador Igual Comillas Identificador Comillas Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DECLARACION ::= Cadena Identificador Igual Comillas Comillas Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARACION ::= Cadena Identificador Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= Bool error Igual Op_booleano Linea 
            {
              Object RESULT =null;
		 
           Errores.add("Se esperaba un identificador despues de Bool\n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= Bool Identificador Igual Op_booleano Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARACION ::= Bool Identificador Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECLARACION ::= Num Identificador Igual OPERACION Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DECLARACION ::= Num Identificador Igual Corchete_a LISTA_NUMEROS Corchete_c Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // DECLARACION ::= Num Identificador Linea 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= MOSTRAR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= SENTENCIA_SIMPLE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= SENTENCIA FOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= SENTENCIA WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= IF_ELSE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= SENTENCIA IF_ELSE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= IF 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIA ::= SENTENCIA IF 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // SENTENCIA ::= SENTENCIA DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= Inicio Llave_a Linea SENTENCIA Llave_c error 
            {
              Object RESULT =null;
		 
           Errores.add("Se esperaba Fin despues del corchete \n");
         
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= Inicio Llave_a Linea SENTENCIA Llave_c Fin 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

