
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 30 11:26:10 CST 2025
//----------------------------------------------------

package analizadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 30;
  public static final int Coma = 10;
  public static final int Llave_c = 7;
  public static final int Op_booleano = 31;
  public static final int Llave_a = 6;
  public static final int If = 20;
  public static final int ResolverSistema = 17;
  public static final int Else = 21;
  public static final int Corchete_c = 9;
  public static final int Corchete_a = 8;
  public static final int Concatenacion = 32;
  public static final int While = 22;
  public static final int Cadena = 13;
  public static final int Parentesis_c = 5;
  public static final int Fin = 19;
  public static final int Parentesis_a = 4;
  public static final int For = 23;
  public static final int EOF = 0;
  public static final int P_coma = 11;
  public static final int error = 1;
  public static final int Mostrar = 16;
  public static final int Linea = 2;
  public static final int Ecuacion = 15;
  public static final int ERROR = 35;
  public static final int Num = 12;
  public static final int Op_logico = 28;
  public static final int Inicio = 18;
  public static final int Identificador = 33;
  public static final int Resta = 26;
  public static final int Bool = 14;
  public static final int Multiplicacion = 27;
  public static final int Op_incremento = 29;
  public static final int Numero = 34;
  public static final int Suma = 25;
  public static final int Igual = 24;
  public static final int Comillas = 3;
}

