
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 30 21:24:17 CST 2025
//----------------------------------------------------

package analizadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 31;
  public static final int Coma = 11;
  public static final int Llave_c = 8;
  public static final int Op_booleano = 32;
  public static final int Llave_a = 7;
  public static final int If = 21;
  public static final int ResolverSistema = 18;
  public static final int Else = 22;
  public static final int Corchete_c = 10;
  public static final int Corchete_a = 9;
  public static final int Concatenacion = 33;
  public static final int While = 23;
  public static final int Cadena = 14;
  public static final int Parentesis_c = 6;
  public static final int Fin = 20;
  public static final int Parentesis_a = 5;
  public static final int For = 24;
  public static final int EOF = 0;
  public static final int P_coma = 12;
  public static final int error = 1;
  public static final int Mostrar = 17;
  public static final int Linea = 2;
  public static final int Ecuacion = 16;
  public static final int ERROR = 36;
  public static final int Num = 13;
  public static final int Op_logico = 29;
  public static final int Symbol = 3;
  public static final int Inicio = 19;
  public static final int Identificador = 34;
  public static final int Resta = 27;
  public static final int Bool = 15;
  public static final int Multiplicacion = 28;
  public static final int Op_incremento = 30;
  public static final int Numero = 35;
  public static final int Suma = 26;
  public static final int Igual = 25;
  public static final int Comillas = 4;
}

